server:
  port: 8889

eureka:
  instance:
    hostname: 127.0.0.1 # 设置主机名B
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/ # localhost 为集群的服务器A

spring:
  application:
    name: eureka-cluster-server