#server:
#  port: 8888
#
#eureka:
#  instance:
#    hostname: localhost # 设置主机名
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:8889/eureka/
#
#spring:
#  application:
#    name: eureka-cluster-server